api_platform:
    title: 'API Walk of Art'
    version: '0.0.3'

    enable_entrypoint: false

    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    formats:
        json:
            mime_types: ['application/json']
        html:
            mime_types: [ 'text/html' ]
        multipart:
            mime_types: [ 'multipart/form-data' ]

    swagger:
        versions: [3]