vich_uploader:
  db_driver: orm

  mappings:
      post_work_files:
          uri_prefix: /files/work_files
          upload_destination: '%kernel.project_dir%/public/files/work_files'
          namer: Vich\UploaderBundle\Naming\SmartUniqueNamer